JiejayLan/CSC322_group_project

src/components/RegisterForm.js, src/components/RegisterPage.js
basic input pattern checking through regex
=> add user input validation to RegisterForm.js

package-lock.json, package.json, public/index.html, server/server.js, src/components/DashboardPage.js
Reverts JiejayLan/CSC322_group_project#22
=> Revert "add watch and reload"

src/components/ItemPage.js
Data returned from query still requires processing, otherwise the items page queries the database for the item whose id is specified in the endpoint ('/items/:id').
=> Item page queries database for item based on item's id specified in path

server/controller/SUmanage_controller.js, server/server.js, src/actions/SUaction.js, src/components/SUhomePage/ItemApplicationList.js, src/components/SUhomePage/UserApplicationList.js, src/components/SUhomePage/UserList.js, src/pages/HomePage.js, src/pages/SUhomePage.js, src/reducers/SUmanagement.js, src/routers/AppRouter.js, src/routers/SuperRoute.js, src/store/configureStore.js
finished the front-end of SU homepage, add SU route, but still using private route for SU homepage now just for the sake of easier access. Add in actions of approve and reject a user application, an approved application will create a new user with status set to newUser, reject will just remove the ref node in firebase
=> SU page/actions/reducer/server_controller

src/components/ProfileForm.js, src/pages/EditProfilePage.js
RegisterPage no longer have the password input field
=> setup a separate form called ProfileForm for EditProfilePage

src/pages/ProfilePage.js
ProfilePage now will update after user submited editProfileForm without the need of a refresh.
=> change ProfilePage into a stateless component

src/pages/LoginPage.js, src/pages/SendMessagePage.js, src/routers/AppRouter.js
1.update complain status
2.warning for first login user
=> update message system and login page

server/controller/auth_controller.js, server/controller/message_controller.js, server/service/messageManager.js, src/components/Header.js, src/pages/LoginPage.js, src/pages/SendMessagePage.js, src/routers/AppRouter.js
1.update the nav bar for different user
2.use new promise to rewrite the message system controller
=> update the nav bar for different user

src/app.js, src/components/transactionPage/BuyItem.js, src/components/transactionPage/GradeSellerModal.js, src/styles/components/_button.scss
a modal will pop up to ask OU submit a rating by clicking "Grade Seller" button on completed orders.
=> add static modal to transactionHistory Page

server/controller/transaction_controller.js, src/components/Header.js, src/components/transactionPage/BuyItem.js, src/components/transactionPage/GradeSellerModal.js, src/routers/AppRouter.js
1. delete the profile tab from Header.js
2. delete /profile path from AppRouter.js
3. after OU submit a rating, seller's grade and rating attributes will be updated in firebase.
=>  grading system now works dynamically

server/controller/friend_controller.js, server/controller/message_controller.js, server/server.js, server/service/FriendManager.js, server/service/messageManager.js, src/pages/FriendPage.js, src/pages/LoginPage.js, src/routers/AppRouter.js
1.add friend
2.delete friend
3.show all friends
4.check if friend
=> friend system

src/actions/SUaction.js, src/components/SUhomePage/ItemApplicationList.js, src/components/SUhomePage/UserList.js
now can formly reject item application, SU has the option to inspect an OU and can view his or her rating also warning times, thus the SU can decide if the OU should be warned or not. Also update a increase warning count action in SU action, will call this action if SU successfully warn an OU later
=> Item application handler, SU inspect OU for grade and warning count, update warning action in SU action

server/controller/SUmanage_controller.js, src/actions/SUaction.js, src/components/SUhomePage/ComplaintList.js, src/components/SUhomePage/UserList.js, src/pages/SendMessagePage.js
added in SU actions about adding username and item to black list, warning count of a certain OU will be increase automatically after a SU sent a warning message, and the OU will be suspend automatically if his or her warn count is larger than or equal to 2, justify complain and remove handler finished
=> Added black list handlers, correct actions on warning, suspend automatically, and complain handlers

src/actions/VIPCheck.js, src/components/Header.js, src/components/RegisterForm.js, src/components/transactionPage/GradeSellerModal.js, src/pages/UserInfoPage.js
VIPCheck.js is located under src/actions. It contains two functions:
- VIPCheckSpending: check OU's spending and warning
- VIPCheckRating : check OU's rating 
New user_type added firebase: VIP OU
When OU promoted to VIP, his/her user_type becomes "VIP OU"
=> utility function VIPCheck added to promote/demote OU

server/service/ItemManager.js
Code changes:
1. Implemented `ItemManager.Store.getAll()` to retrieve all items from the database
@RyanLinrm
=> Implemented Store.getAll() to retrieve all items

src/actions/usernameCheck.js, src/components/ProfileForm.js, src/components/SubmittedItemApp.js, src/pages/EditProfilePage.js, src/pages/RegisterPage.js
Both forms now check:
1. username is unique 
2. username does not contain taboo words
3. username is not in blacklist [for RegisterForm]
=> RegisterForm and ProfileForm checks username 

server/AuctionCheck.js, server/controller/item_page_controller.js, server/service/OrderManager.js, src/pages/ItemPage.js
Major code changes:
1. `OrderManager.createPendingOrder()` adds the ID of buyer/seller to the created order and no longer adds the seller's name
=> Refactored OrderManager.createPendingOrder()

server/service/OrderManager.js, src/pages/ItemPage.js
Code changes:
1. Made adjustments to use `Item.title`
=> Changed Item.name to Item.title

server/controller/taboo_controller.js, server/server.js, src/actions/taboo.js, src/pages/LoginPage.js, src/pages/sellItemForm.js, src/reducers/taboo.js, src/store/configureStore.js
1. the sell new item form will check if the item is under blacklist
2.the login page will load the taboo list into the redux
=> add taboolist and blacklist

server/controller/submittedItem_controller.js, server/controller/transaction_controller.js, server/server.js, src/actions/getUserProfile.js, src/components/SubmittedItemApp.js, src/components/transactionPage/BuyItem.js, src/components/transactionPage/SellItem.js, src/pages/UserInfoPage.js
UserInfoPage now display on-sell items' title and keywords. 
@JiejayLan
=> Display On-sell items on UserInfoPage

server/controller/process_pending_order_controller.js, server/server.js, server/service/OrderManager.js, src/pages/ItemPage.js
Major code changes:
1. Implemented the logic for the endpoint _/process-pending-orders/reject/:orderId_ for rejecting pending orders.
2. Implemented `OrderManager.getOne()` and `OrderManager.update()`.
Major database changes:
1. The `status` of rejected _/orders_ is set to `"rejected"` and the `status` of the corresponding _/items_ is set to `"expired"`.
2. A new _/message_  from the seller to the buyer is created with an explanation for rejecting the buyer.
=> Implemented handling of requests to process pending orders

src/components/Header.js, src/function/checkTaboo.js, src/pages/EditItemPage.js, src/pages/sellItemForm.js, src/routers/AppRouter.js, src/store/configureStore.js
allow user to edit item's keyword and title
=> add edit item page

src/actions/SUaction.js, src/components/SUhomePage/ItemApplicationList.js, src/components/SUhomePage/SUviewItems.js, src/pages/SUhomePage.js
Fixed some code with changed database format, approve item application finished, and after the application got approved, whoever subscribes to the associated keywords of this new item will be notified about this item, all I did is just push a new message into the database
=> Notify ou when an item with matched keyword is up

src/components/SubmittedItemApp.js, src/components/transactionPage/BuyItem.js, src/components/transactionPage/SellItem.js, src/pages/EditItemPage.js, src/styles/components/_button.scss
1. added "Approve Buyer" button in Selling Items that redirects users to SellerApproveItem page
2. added "Order Checkout" button in Buying Items (currently redirects to TransactionHistory Page, will change "to" attribute after checkout page is set up.)
@shiBinH
=> add buttons to TransactionHistoryPage

src/components/RandomPrize.js, src/routers/AppRouter.js
@shiBinH 
you can add <RandomPrize/> to Checkout once you setup Checkout page.
=> added RandomPrize.js componet for checkout

server/controller/taboo_controller.js, src/function/checkTaboo.js, src/function/test.js, src/pages/EditItemPage.js, src/pages/LoginPage.js, src/pages/sellItemForm.js, src/store/configureStore.js
add two taboo functions inside the function folder, which can be used to convert and check taboo word
=> add taboo functions 

src/components/transactionPage/SellItem.js, src/routers/AppRouter.js
redirect OUs to `sellerapprove/:orderid ` after he/she clicked Approve Buyer button.
@shiBinH
=> modified route to SellerApprovePage to sellerapprove/:orderid

src/actions/application.js, src/components/ProfileForm.js, src/components/RegisterForm.js, src/components/transactionPage/BuyItem.js
New attribute added to Users for Firebase: address_state
@RyanLinrm 
@shiBinH
=> address_state attribute added

src/components/Header.js, src/pages/EditProfilePage.js
Reverts JiejayLan/CSC322_group_project#117
=> Revert "change user_type to OU after new user change password"

server/controller/checkout_controller.js, server/controller/process_pending_order_controller.js, server/server.js, server/service/FriendManager.js, src/pages/CheckoutPage.js, src/pages/SellerApproveItemPage.js, src/routers/AppRouter.js
Major application changes:
1. Sellers can approve/reject orders.
2. Buyers can move to the checkout page _/checkout/:orderid_ to confirm their order. Actual confirming has not been implemented yet. 
Major code changes:
1. Added route and controller for order checkout page
2. Connect seller approval page to its controller
=> Added page for order checkout

server/controller/checkout_controller.js, src/pages/CheckoutPage.js
Major application changes:
1. Buyers can finalize their order in the checkout page _/checkout/:orderid_.
2. Checkout page dynamically changes based on success of checkout.
Major codes changes:
1. Implemented `onPlaceYourOrder()` in _/pages/Checkoutpage.js_ 
2. Added `message` attribute to state of  _/pages/Checkoutpage.js_ 
Major database changes:
1. Successful checkouts changes `status` of _/orders_ from `approved `to `completed`
=> Completed order checkout functionality

server/controller/checkout_controller.js, src/pages/CheckoutPage.js
Major code changes:
1. Added a state sales tax table to `checkout_controller.js`
=> State tax is now computed based on buyer's state

public/index.html, src/components/RandomPrize.js, src/pages/CheckoutPage.js
=> add random prize generator to CheckoutPage

src/components/Header.js, src/components/messgePage/MessageOption.js, src/pages/EditItemPage.js, src/pages/sellItemForm.js
=> change message page user type

src/pages/ItemPage.js
Major application changes:
1. The item page displays the seller's username instead of ID
=> ItemPage now displays seller's username instead of ID

server/controller/checkout_controller.js, server/controller/process_pending_order_controller.js, src/pages/SellerApproveItemPage.js
Major application changes:
1. Successful checkouts adds the transaction total to seller's balance
2. Page for approving/rejecting items contains a message box to report status of order processing
3. Successful order approvals/rejections redirects the user to the transaction page
=> Updates to checkout and order approval/rejection

src/pages/ItemPage.js
I removed the description from Item Page.
@shiBinH 
@RyanLinrm
=> remove description from ItemPage.js
